### ISSUE TITLE
.18

### ISSUE THREAD

**Issue by converge** [phcollignon/helm3#12]
I'm running Minikube 1.12 and Kubernetes 1.18, when I try to apply the first exercise with
```
kubectl apply -f frontend.yaml
```
it shows:
```
The Deployment "frontend" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"frontend"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

*It works with Docker Kubernetes.

**Comment by phcollignon** [comment]
Hello, I tried to replicate on the following environment following the steps in the course (Module 4, clip 2) : 
- Minikube 1.12.3 running in a VirtualBox 6.1 VM on Linux
- Kubernetes 1.18.3 
But I did not have any error.  
Please could you tell me on which environment you are running Minikube :  VM driver and host operating system ?
Could you also simply delete the object "kubectl delete -f frontend.yaml" and create it again, that "field immutable" error might be related to an existing object.
Regards,

**Comment by converge** [comment]
thanks for the prompt reply, and for the great PluralSight course about Helm.
I did a reset for Minikube, and now it works. thank you!
