### ISSUE TITLE
CORS erros when running the samples

### ISSUE THREAD

**Issue by thomashoefkens-vw** [phcollignon/helm3#15]
Hi @Philippe-Collignon 

When running e.g. lab6 on minikube with the ingress addon enabled, I get CORS errors when posting a comment.
I have mapped to the minikube ip in the hosts file to both frontend.minikube.local and backend.minikube.local, I can see the frontend with the DNS name but cannot post. What may I be missing here? 

Thanks

<img width="778" alt="Bildschirmfoto 2020-12-12 um 17 51 12" src="https://user-images.githubusercontent.com/71012278/101989716-b42abb80-3ca2-11eb-859f-2aeff31141e0.png">

<img width="783" alt="Bildschirmfoto 2020-12-12 um 17 52 28" src="https://user-images.githubusercontent.com/71012278/101989740-d1f82080-3ca2-11eb-9d9f-4a31e40225cb.png">

**Comment by thomashoefkens-vw** [comment]
Guess this may be the cause:
<img width="490" alt="Bildschirmfoto 2020-12-12 um 17 54 11" src="https://user-images.githubusercontent.com/71012278/101989797-197eac80-3ca3-11eb-8e8c-59d8f0ef115f.png">

**Comment by phcollignon** [comment]
Hello Thomas,
Sorry I saw your case too late.  As you closed it you may have found the issue.
CORS is allowed in a very permissive way in the `server.js` file so it should be another reason.
Regards,
Philippe

**Comment by thomashoefkens-vw** [comment]
Hi Philippe,


I managed to solve it on my Mac by running

minikube stop && minikube delete && minikube start --vm=true --driver=hyperkit

And then installing the add-on ingress for minikube.

After then installing the Chart with helm, all pods came up correctly.


And, by the way, thanks for the great course! It is really well structured and very informative/easy to learn that way!

Thomas


Am 12.12.2020 um 18:45 schrieb Philippe Collignon <notifications@github.com<mailto:notifications@github.com>>:



Hello Thomas,
Sorry I saw your case too late. As you closed it you may have found the issue.
CORS is allowed in a very permissive way in the server.js file so it should be another reason.
Regards,
Philippe
