### ISSUE TITLE
Lab 1 Missing Ingress Controller in Windows

### ISSUE THREAD

**Issue by lixiong-intelex** [phcollignon/helm3#7]
Hi Philippe,

I am following your pluralsight course and tries to do lab 1.

However I cannot open http://frontend.minikube.local/, seems cannot hit the endpoint. 
![image](https://user-images.githubusercontent.com/31544870/80969302-646c4380-8de7-11ea-8ab6-40a39226d815.png)

I am using Docker Desktop for Windows, seems it doesn't come with Ingress Controller. I then installed it through https://kubernetes.github.io/ingress-nginx/deploy/#bare-metal. Still doesn't work.

Is there something I am still missing? Can you please point me to the right direction?

Thanks!

**Comment by phcollignon** [comment]
Hello, you have to expose the IP of the ingress to the host (I'm not used with docker desktop; it is something like "docker run -p ...") and resolve frontend.minikube.local to the host IP. (Be sure also that your kubernetes instance supports ingress .. ) (you can get the ingress IP with "kubectl get ingress")  If you cannot get it working you can use minikube in a VM as described in the course.

**Comment by lixiong-intelex** [comment]
Thanks! Will give it a try.

**Comment by lixiong-intelex** [comment]
Eventually found out that need to stop other services that are listening on port 80, in my case, IIS.
